### ISSUE TITLE
Midi mixer cpu usage very high when you use snipping tool.

### ISSUE THREAD

**Issue by LuciusAezerith** [jpwilliams/midi-mixer-releases#10] opened 2021-02-01 14:04 UTC
**Describe the bug** 

Midi mixer core cpu usage very high when you use snip and sketch

**To Reproduce**

1. Have midi mixer running in the background
2. Open snip and sketch with print screen button or open snip and sketch and keep it in focus
3. See error

**Expected behavior**

Normal CPU usage.

**Screenshots**

![image](https://user-images.githubusercontent.com/57662283/106468711-97d71e00-649e-11eb-9f6c-3ad374422588.png)
![image](https://user-images.githubusercontent.com/57662283/106471659-2600d380-64a2-11eb-9d43-f6da718c2aed.png)

**Build:**

 - Version 2.2.2 

**Additional context**

cpu being used when experiencing this error: amd ryzen 7 5800x.

**Comment by jpwilliams** [comment] 2021-02-01 14:45
Great bug report. Can reproduce over here too. Will investigate this evening. :)

**Comment by jpwilliams** [comment] 2021-02-01 18:52
@RaphaelVandenBergh Would it be possible for you to DM me on [Discord](https://discord.midi-mixer.com) (or another private means of communication) and I can push out a test build to you to see if the problem is resolved?

**Comment by LuciusAezerith** [comment] 2021-02-02 15:20
@jpwilliams I've send you a dm on discord as Lucius.

**Comment by jpwilliams** [comment] 2021-02-07 13:58
After testing with @RaphaelVandenBergh, this is fixed in [v2.2.3](https://github.com/jpwilliams/midi-mixer-releases/releases/tag/v2.2.3).

**Closed as completed by jpwilliams** 2021-02-07 13:58 UTC
Labels: bug
